"""order_status

Revision ID: b6e912dddcb6
Revises: 2fd536c11eb0
Create Date: 2025-01-01 02:06:20.123179

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b6e912dddcb6"
down_revision: Union[str, None] = "2fd536c11eb0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column(
            "status", sa.String(length=50), nullable=False, server_default="pending"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "status")
    # ### end Alembic commands ###
